// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeajTgn6sJjzlypiVy6blLMvIPCjTPyME',
    appId: '1:982542597893:android:4043291bde592c1750416c',
    messagingSenderId: '982542597893',
    projectId: 'taxi-calculates',
    storageBucket: 'taxi-calculates.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyCcmwUMOXI5JC29dnnvJewfPXlbox8Xc',
    appId: '1:982542597893:web:172eba26b0d2895650416c',
    messagingSenderId: '982542597893',
    projectId: 'taxi-calculates',
    authDomain: 'taxi-calculates.firebaseapp.com',
    storageBucket: 'taxi-calculates.appspot.com',
    measurementId: 'G-6BKL5WRSFS',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkXpTiU7K51_PBbILFu8h0MaCghugJZSw',
    appId: '1:982542597893:ios:c6822745dd75c7f450416c',
    messagingSenderId: '982542597893',
    projectId: 'taxi-calculates',
    storageBucket: 'taxi-calculates.appspot.com',
    iosBundleId: 'com.example.taxiCalculate',
  );

}